apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp_log
  labels:
    app: webapp_log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp_log
  template:
    metadata:
      labels:
        app: webapp_log
    spec:
      containers:
      - name: webapp_log
        image: webapp_log:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: webapp_log-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: webapp_log

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp_log-ingress
  labels:
    app: webapp_log-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: webapp_log-service
          servicePort: 80