apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplog
  labels:
    app: webapplog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplog
  template:
    metadata:
      labels:
        app: webapplog
    spec:
      containers:
      - name: webapplog
        image: webapplog:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: webapplog-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: webapplog

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapplog-ingress
  labels:
    app: webapplog-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: webapplog-service
          servicePort: 80