version: "3.9"  # optional since v1.27.0
services:
  loki:
      image: grafana/loki:master
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      networks:
        - loki
  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
  webapi:
    image: logapp
    ports:
      - "5000:80"
    networks:
      - loki

networks:
  loki: